qubes-prepare-vm-kernel: sync with pre-built package features
Several changes:
 - build with mkfs.ext3 -d (doesn't require root, easier achieve
   reproducible output)
 - optionally include kernel headers
 - post-process with vm-modules-genfs for SELinux labels
 - option to build just modules.img (to be used from kernel-qubes-vm
   package post-install script)

QubesOS/qubes-issues#7969

(cherry picked from commit c3fcb0f02277733067ba75000bafa7d94f47ee99)

diff --git a/kernel-modules/qubes-prepare-vm-kernel b/kernel-modules/qubes-prepare-vm-kernel
--- a/kernel-modules/qubes-prepare-vm-kernel
+++ b/kernel-modules/qubes-prepare-vm-kernel
@@ -28,18 +28,34 @@ basedir=/var/lib/qubes/vm-kernels
 function build_modules_img() {
     kver=$1
     initramfs=$2
-    output_file=$3
+    kernel=$3
+    output_file=$4
 
-    mkdir /tmp/qubes-modules-$kver
-    truncate -s 400M /tmp/qubes-modules-$kver.img
-    mkfs -t ext3 -F /tmp/qubes-modules-$kver.img > /dev/null
-    mount /tmp/qubes-modules-$kver.img /tmp/qubes-modules-$kver -o loop
-    cp -a -t /tmp/qubes-modules-$kver /lib/modules/$kver
-    cp "/boot/vmlinuz-$kver" "/tmp/qubes-modules-$kver/vmlinuz"
-    cp "$initramfs" "/tmp/qubes-modules-$kver/initramfs"
-    umount /tmp/qubes-modules-$kver
-    rmdir /tmp/qubes-modules-$kver
-    mv /tmp/qubes-modules-$kver.img $output_file
+    local tmpdir
+    tmpdir=$(mktemp -d -p /var/tmp)
+
+    mkdir "$tmpdir/modules"
+    cp -a -t "$tmpdir/modules" /lib/modules/$kver
+    cp "$kernel" "$tmpdir/modules/vmlinuz"
+    cp "$initramfs" "$tmpdir/modules/initramfs"
+
+    rm -f "$tmpdir/modules/$kver/build"
+    if [ "$include_devel" ]; then
+        cp -a "/usr/src/kernels/$kver" "$tmpdir/modules/$kver/build"
+    fi
+
+    flags="-Enum_backup_sb=0,root_owner=0:0,no_copy_xattrs"
+    flags="$flags,hash_seed=dcee2318-92bd-47a5-a15d-e79d1412cdce"
+    PATH=/usr/sbin:/sbin:$PATH mkfs.ext3 -q -F "$flags" \
+        -d "$tmpdir/modules" "$tmpdir/modules.img" 768M
+    /usr/lib/qubes/vm-modules-genfs "$tmpdir/modules.img" "$kver" immutable=yes
+    e2fsck -pDfE optimize_extents -- "$tmpdir/modules.img" >/dev/null
+    resize2fs -M -- "$tmpdir/modules.img" >/dev/null
+    e2fsck -pDfE optimize_extents -- "$tmpdir/modules.img" >/dev/null
+    /usr/lib/qubes/vm-modules-genfs "$tmpdir/modules.img"
+
+    mv "$tmpdir/modules.img" $output_file
+    rm -rf "$tmpdir"
 }
 
 function build_initramfs() {
@@ -54,31 +70,74 @@ function build_initramfs() {
     chmod 644 "$output_file"
 }
 
-if [ -z "$1" ]; then
-    echo "Usage: $0 <kernel-version> [<display-kernel-version>]" >&2
-    exit 1
+function usage() {
+    echo "Usage: qubes-prepare-vm-kernel [--modules-only] [--include-devel] <kernel-version> [<display-kernel-version>]" >&2
+    echo "  --modules-only - only build modules.img, vmlinuz is expected to be present already" >&2
+    echo "  --include-devel - include kernel headers in modules.img, requires kernel-devel pkg installed" >&2
+    exit 2
+}
+
+modules_only=
+include_devel=
+
+while [ -n "$1" ]; do
+    case "$1" in
+    --modules-only)
+        modules_only=1
+        shift
+        ;;
+    --include-devel)
+        include_devel=1
+        shift
+        ;;
+    --*) usage;;
+    *) break;;
+    esac
+done
+
+if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
+    usage
 fi
 
-if [ ! -r /boot/vmlinuz-$1 -o ! -d /lib/modules/$1 ]; then
-    echo "ERROR: Kernel version $1 not installed" >&2
-    exit 1
-fi
-
-kernel_version=$1
+kernel_version="$1"
 if [ -n "$2" ]; then
     output_dir="$basedir/$2"
 else
     output_dir="$basedir/$kernel_version"
 fi
 
+
+if [ ! -d "/lib/modules/$kernel_version" ]; then
+    echo "ERROR: Modules version $kernel_version not installed" >&2
+    exit 1
+fi
+
+if [ ! "$modules_only" ] && [ ! -r "/boot/vmlinuz-$kernel_version" ]; then
+    echo "ERROR: Kernel version $kernel_version not installed" >&2
+    exit 1
+fi
+
+if [ "$modules_only" ] && [ ! -r "$output_dir/vmlinuz" ]; then
+    echo "ERROR: --modules-only requires '$output_dir/vmlinuz' to already exist" >&2
+    exit 1
+fi
+
+if [ "$include_devel" ] && [ ! -d "/usr/src/kernels/$kernel_version" ]; then
+    echo "ERROR: --include-devel requires kernel-devel package (containing '/usr/src/kernels/$kernel_version')" >&2
+    exit 1
+fi
+
 echo "--> Building files for $kernel_version in $output_dir"
 
-mkdir -p "$output_dir"
-cp "/boot/vmlinuz-$kernel_version" "$output_dir/vmlinuz"
-echo "---> Generating initramfs"
-build_initramfs "$kernel_version" "$output_dir/initramfs"
+if ! [ "$modules_only" ]; then
+    mkdir -p "$output_dir"
+    cp "/boot/vmlinuz-$kernel_version" "$output_dir/vmlinuz"
+    echo "---> Generating initramfs"
+    build_initramfs "$kernel_version" "$output_dir/initramfs"
+fi
 echo "---> Generating modules.img"
 build_modules_img "$kernel_version" "$output_dir/initramfs" \
+    "$output_dir/vmlinuz" \
     "$output_dir/modules.img"
 
 echo "--> Done."
